//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolStudent
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int CurrentSchool { get; set; }
        public Nullable<int> PreviousSchool1 { get; set; }
        public Nullable<int> PreviousSchool2 { get; set; }
        public Nullable<int> PreviousSchool3 { get; set; }
    
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        public virtual School School2 { get; set; }
        public virtual School School3 { get; set; }
        public virtual Student Student { get; set; }
    }
}
