//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Observation { get; set; }
        public string Intervention { get; set; }
        public string Response { get; set; }
        public int LangProficiencyLevelID { get; set; }
    
        public virtual LangProficiencyLevel LangProficiencyLevel { get; set; }
    }
}
